name: default

on:
  push:
    branches:
      - "**"
      - "!experiment-*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: colcon_ws/src
      - name: Clone additional repositories
        run: |
          cd ${GITHUB_WORKSPACE}/colcon_ws
          git clone -b 3.2.7 https://github.com/google-deepmind/mujoco.git
          git clone https://github.com/rxdu/mujoco_ros2_control.git
          git clone https://github.com/rxdu/mujoco_demo_robot.git
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libxinerama-dev libxcursor-dev libxi-dev
          sudo apt-get install -y ros-jazzy-ros2-control ros-jazzy-ros2-controllers
      - name: Additional ROS dependencies
        run: |
          apt update
          apt install -y python3-rosdep
          if [ ! -e /etc/ros/rosdep/sources.list.d/20-default.list ]; then rosdep init; fi
          cd ${GITHUB_WORKSPACE}/colcon_ws
          source /opt/ros/${ROS_DISTRO}/setup.bash
          rosdep update
          rosdep install -y -r --ignore-src --from-paths src --rosdistro ${ROS_DISTRO}
      - name: Colcon build
        run: |
          cd ${GITHUB_WORKSPACE}/colcon_ws
          source /opt/ros/${ROS_DISTRO}/setup.bash
          colcon build --symlink-install --cmake-args " -DCMAKE_BUILD_TYPE=Release"